apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deploy
  labels:
    app: webpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: cont1
        image: riteshprasad07/devopsbyritesh07:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: LoadBalancer
  selector:
    app: webpage
  ports:
  - port: 3000     
    targetPort: 80
    protocol: TCP
